steal('funcunit/syn',
	'funcunit/browser/core.js', 
	'funcunit/browser/adapters/adapters.js',
	'funcunit/browser/open.js', 
	'funcunit/browser/actions.js', 
	'funcunit/browser/getters.js',
	'funcunit/browser/traversers.js', 
	'funcunit/browser/queue.js', 
	'funcunit/browser/waits.js');